In [88]:
import pandas as pd
import numpy as np

In [4]:
## series of 1-D array

s = pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [5]:
pop = pd.Series([1444,1939,3257,845],index = ["India","China","USA","Indonesia"],name = "population_millions")
print(pop)

India        1444
China        1939
USA          3257
Indonesia     845
Name: population_millions, dtype: int64

In [8]:
print(pop[pop>1500])

China    1939
USA      3257
Name: population_millions, dtype: int64

In [10]:
q1 = pd.Series({"laptops":120,"phone":340,"tablets":77})
q2 = pd.Series({"phone":44,"laptops":474,"wathce":73})

print(q1 + q2)

laptops    594.0
phone      384.0
tablets      NaN
wathce       NaN
dtype: float64

## Data Frames

In [15]:
df = pd.DataFrame({
    "Name":["Furkan","Giri","Preet","Diya","Evan"],
    "dept": ["MLAI","Finance","MLAI","IT","HR"],
    "Salary":[52000,48000,47999,75000,50000],
    "City": ["Bharuch","Vapi","Surat","Delhi","Mumbai"]
})

In [16]:
print(df)

     Name     dept  Salary     City
0  Furkan     MLAI   52000  Bharuch
1    Giri  Finance   48000     Vapi
2   Preet     MLAI   47999    Surat
3    Diya       IT   75000    Delhi
4    Evan       HR   50000   Mumbai

In [19]:
print(df.shape)
print(list(df.columns))
df.info()
df.describe()
df.head()

(5, 4)
['Name', 'dept', 'Salary', 'City']
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   dept    5 non-null      str
 2   Salary  5 non-null      int64
 3   City    5 non-null      str
dtypes: int64(1), str(3)
memory usage: 292.0 bytes

     Name     dept  Salary     City
0  Furkan     MLAI   52000  Bharuch
1    Giri  Finance   48000     Vapi
2   Preet     MLAI   47999    Surat
3    Diya       IT   75000    Delhi
4    Evan       HR   50000   Mumbai

In [22]:
raw = pd.DataFrame({
    "order_id":["1001","1002","1003"],
    "amount": ["2500","1800","3200"], 
})

In [23]:
print(raw["amount"].sum())

250018003200

In [24]:
clean = raw.copy()

In [27]:
clean["order_id"] = pd.to_numeric(clean["order_id"])
clean["amount"] = pd.to_numeric(clean["amount"])

print(clean["amount"].sum())

7500

In [28]:
df

     Name     dept  Salary     City
0  Furkan     MLAI   52000  Bharuch
1    Giri  Finance   48000     Vapi
2   Preet     MLAI   47999    Surat
3    Diya       IT   75000    Delhi
4    Evan       HR   50000   Mumbai

In [31]:
people = df.set_index("Name")
people

           dept  Salary     City
Name
Furkan     MLAI   52000  Bharuch
Giri    Finance   48000     Vapi
Preet      MLAI   47999    Surat
Diya         IT   75000    Delhi
Evan         HR   50000   Mumbai

In [45]:
print(people.loc["Giri":"Furkan"])

Empty DataFrame
Columns: [dept, Salary, City]
Index: []

In [46]:
print(people.loc[["Diya"],["Salary"]])

      Salary
Name
Diya   75000

In [48]:
print(people.iloc[0])

dept         MLAI
Salary      52000
City      Bharuch
Name: Furkan, dtype: object

In [53]:
print(people.iloc[0:3],[0,2])

           dept  Salary     City
Name
Furkan     MLAI   52000  Bharuch
Giri    Finance   48000     Vapi
Preet      MLAI   47999    Surat [0, 2]

In [54]:
print(people[people["Salary"]<50000])

          dept  Salary   City
Name
Giri   Finance   48000   Vapi
Preet     MLAI   47999  Surat

In [69]:
print(people[(people["dept"] == "IT") & (people["Salary"] > 50000)])

     dept  Salary   City
Name
Diya   IT   75000  Delhi

In [85]:
people.query('dept == "IT"')

     dept  Salary   City
Name
Diya   IT   75000  Delhi

In [92]:
messy = pd.DataFrame({
     "product" : ["pen","book","bag","lamp"],
     "price" : [20,np.nan,850,1200],
     "rating": [4.1,np.nan,4.5,4.5]
 })
print(messy)

  product   price  rating
0     pen    20.0     4.1
1    book     NaN     NaN
2     bag   850.0     4.5
3    lamp  1200.0     4.5

In [93]:
messy.isna()

   product  price  rating
0    False  False   False
1    False   True    True
2    False  False   False
3    False  False   False

In [94]:
messy.isna().sum()

product    0
price      1
rating     1
dtype: int64

In [95]:
filled = messy.copy()

In [98]:
filled["price"] = filled["price"].fillna(filled["price"].mean())

In [99]:
filled["rating"] = filled["rating"].fillna(filled["rating"].median())

In [100]:
print(filled)

  product   price  rating
0     pen    20.0     4.1
1    book   690.0     4.5
2     bag   850.0     4.5
3    lamp  1200.0     4.5

In [101]:
print(people.query('dept == "IT" & Salary >50000'))

     dept  Salary   City
Name
Diya   IT   75000  Delhi